name: pychop3d
dependencies:
   - python=3.7
   - pip
   - matplotlib
   - numpy
   - scipy
   - pytest
   - networkx
   - shapely
   - rtree
   - pyyaml
   - requests
   - pip:
      - trimesh
      - pyglet
# https://www.lfd.uci.edu/~gohlke/pythonlibs/#meshpy for meshpy
